### PR TITLE
Added the Java Code for an Auto Service app

### PR DESCRIPTION
**Pull request by MariaSecu**
Hi guys, please review my code and if something is wrong, let me know. Thank you.

### CODE REVIEW

**Review by arturrusnac — APPROVED** [review]
Nice Job ! 
Code looks good ! 
Is arranged well, and clean !

**Review by DimaSersun — APPROVED** [review]
Good job!!!

**Comment by OleseaRusnac** [comment]
Well done! Good job!

**Review by OleseaRusnac — COMMENTED** [review]
Good job! Well done!

**Pull request merged**
